# Generated by Django 2.0.1 on 2018-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='ladder.Tag'),
        ),
    ]
