# Generated by Django 2.0.7 on 2018-07-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
                ('ladders', models.ManyToManyField(blank=True, to='ladder.Ladder', verbose_name='ラダー')),
            ],
            ),
        migrations.AlterField(
            model_name='tags',
            name='ladders',
            field=models.ManyToManyField(blank=True, related_name='tags', to='ladder.Ladder'),
        ),
    ]
