# Generated by Django 2.0.1 on 2018-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0002_auto_20180726_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladder',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='ladders',
            field=models.ManyToManyField(blank=True, to='ladder.Ladder', verbose_name='ラダー'),
        ),
    ]
