# Generated by Django 2.0.1 on 2018-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_auto_20180730_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='ladder_description',
            field=models.TextField(default=None, null=True, verbose_name='ladderの説明'),
        ),
    ]
