# Generated by Django 2.0.1 on 2018-07-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_merge_20180626_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='latter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latter_ladder', to='ladder.Ladder'),
        ),
        migrations.AlterField(
            model_name='link',
            name='prior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_ladder', to='ladder.Ladder'),
        ),
    ]
