# Generated by Django 2.0.1 on 2018-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0004_ladder_ladder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
