# Generated by Django 2.0.1 on 2018-07-13 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_learningstatus_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ladder.Comment', verbose_name='親コメント')),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='ladder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='ladder.Ladder'),
        ),
        migrations.RemoveField(
            model_name='ladder',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='ladder',
            unique_together={('creater', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='learningstatus',
            unique_together={('user', 'unit')},
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user', 'latter')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('ladder', 'index')},
        ),
        migrations.AddField(
            model_name='comment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Unit', verbose_name='ユニット'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
