# Generated by Django 2.0.1 on 2018-07-12 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_learningstatus_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('target', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ladder.Comment', verbose_name='親コメント')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ladder.Unit', verbose_name='ユニット')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
